UPDATE logs SET y_loc=21 WHERE _id=452;
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(453,'Thaumaturge',1,'Western Thanalan','The Eighty Sins of Sasamo','Little Ladybug',3,28,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(454,'Thaumaturge',1,'Central Thanalan','Spineless Basin','Huge Hornet',3,22,27,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(455,'Thaumaturge',1,'Western Thanalan','The Eighty Sins of Sasamo','Cactuar',3,27,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(456,'Thaumaturge',1,'Central Thanalan','Spineless Basic','Snapping Shrew',3,24,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(457,'Thaumaturge',1,'Central Thanalan','Black Brush','Syrphid Cloud',3,18,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(458,'Thaumaturge',1,'Western Thanalan','Hammerlea','Yarzon Feeder',3,24,27,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(459,'Thaumaturge',1,'Western Thanalan','Hammerlea','Rusty Coblyn',3,20,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(460,'Thaumaturge',1,'Central Thanalan','Sil''dih Excavation Site','Spriggan Groverobber',3,16,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(461,'Thaumaturge',1,'Central Thanalan','The Rat''s Nest','Qiqirn Shellsweeper',3,17,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(462,'Thaumaturge',1,'Central Thanalan','The Clutch','Sun Bat',3,26,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(463,'Thaumaturge',2,'Western Thanalan','Horizon''s Edge','Bomb',3,27,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(464,'Thaumaturge',2,'Western Thanalan','Horizon''s Edge','Copper Coblyn',2,27,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(465,'Thaumaturge',2,'Central Thanalan','The Clutch','Cochineal Cactuar',3,23,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(466,'Thaumaturge',2,'Central Thanalan','The Clutch','Quiveron Attendant',2,23,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(467,'Thaumaturge',2,'Central Thanalan','Black Brush','Antling Sentry',3,16,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(468,'Thaumaturge',2,'Western Thanalan','The Eighty Sins of Sasamo','Giant Tortoise',2,21,26,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(469,'Thaumaturge',2,'Western Thanalan','The Footfalls','Thickshell',3,16,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(470,'Thaumaturge',2,'Central Thanalan','The Clutch','Toxic Toad',3,27,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(471,'Thaumaturge',2,'Eastern Thanalan','Sandgate','Tuco-tuco',3,15,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(472,'Thaumaturge',2,'Eastern Thanalan','Drybone','Myotragus Nanny',3,18,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(473,'Thaumaturge',2,'Eastern Thanalan','Drybone','Blowfly Swarm',3,12,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(474,'Thaumaturge',2,'Eastern Thanalan','Drybone','Rotting Corpse',1,15,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(475,'Thaumaturge',2,'Western Thanalan','The Footfalls','Bloated Bogy',3,13,11,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(476,'Thaumaturge',3,'East Shroud','Nine Ivies','Overgrown Ivy',4,23,29,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(477,'Thaumaturge',3,'South Shroud','Upper Paths','Kedtrap',2,21,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(478,'Thaumaturge',3,'Upper La Noscea','Oakwood','Forest Yarzon',4,11,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(479,'Thaumaturge',3,'Western Thanalan','The Footfalls','Yarzon Scavenger',2,15,8,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(480,'Thaumaturge',3,'Western Thanalan','The Footfalls','Laughing Toad',4,15,7,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(481,'Thaumaturge',3,'South Shroud','Upper Paths','Bark Eft',2,17,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(482,'Thaumaturge',3,'East Shroud','The Bramble Patch','Jumping Djigga',4,15,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(483,'Thaumaturge',3,'East Shroud','The Bramble Patch','Glowfly',2,15,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(484,'Thaumaturge',3,'South Shroud','Silent Arbor','River Yarzon',4,23,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(485,'Thaumaturge',3,'Southern Thanalan','Broken Water','Potter Wasp Swarm',4,20,9,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(486,'Thaumaturge',3,'Eastern Thanalan','Wellwick Wood','Phurble',4,23,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(487,'Thaumaturge',3,'Southern Thanalan','Broken Water','Corpse Brigade Knuckledancer',4,24,9,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(488,'Thaumaturge',3,'Southern Thanalan','The Red Labyrinth','Fire Sprite',4,13,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(489,'Thaumaturge',3,'Central Shroud','Sorrel Haven','Stroper',4,12,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(490,'Thaumaturge',4,'Upper La Noscea','Bronze Lake','Mamool Ja Executioner',5,27,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(491,'Thaumaturge',4,'South Shroud','Lower Paths','Adamantoise',2,16,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(492,'Thaumaturge',4,'Southern Thanalan','Sagolii Desert','Russet Yarzon',5,14,32,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(493,'Thaumaturge',4,'Central Shroud','Sorrel Haven','Revenant',2,12,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(494,'Thaumaturge',4,'Southern Thanalan','Sagolii Desert','Smoke Bomb',5,19,35,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(495,'Thaumaturge',4,'Eastern La Noscea','Raincatcher Gully','Dung Midge Swarm',2,18,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(496,'Thaumaturge',4,'Eastern La Noscea','Raincatcher Gully','Gigantoad',5,18,26,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(497,'Thaumaturge',4,'Central Shroud','The Standing Corses','Spriggan',2,11,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(498,'Thaumaturge',4,'Upper La Noscea','Bronze Lake','Salamander',5,28,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(499,'Thaumaturge',4,'Outer La Noscea','Iron Lake','Plasmoid',5,25,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(500,'Thaumaturge',4,'Coerthas Central Highlands','Dragonhead','Ice Sprite',5,20,31,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(501,'Thaumaturge',4,'Coerthas Central Highlands','Dragonhead','Feral Croc',5,26,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(502,'Thaumaturge',4,'South Shroud','Snakemolt','Will-o''-the-Wisp',5,23,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(503,'Thaumaturge',4,'Eastern Thanalan','The Burning Wall','Golden Fleece',5,27,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(504,'Thaumaturge',5,'Coerthas Central Highlands','Whitebrim','Dragonfly',6,9,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(505,'Thaumaturge',5,'East Shroud','Larkscall','Old-Growth Treant',2,25,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(506,'Thaumaturge',5,'Western La Noscea','The Isles of Umbra','Dead Man''s Moan',6,15,34,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(507,'Thaumaturge',5,'Central Shroud','The Standing Corses','Crator Golem',1,10,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(508,'Thaumaturge',5,'East Shroud','Larkscall','Morbol',6,23,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(509,'Thaumaturge',5,'East Shroud','Larkscall','3rd Cohort Secutor',2,32,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(510,'Thaumaturge',5,'Mor Dhona','Fogfens','Nix',6,19,9,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(511,'Thaumaturge',5,'South Shroud','Urth''s Gift','Lesser Kalong',2,28,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(512,'Thaumaturge',5,'Coerthas Central Highlands','Boulder Downs','Giant Logger',3,13,25,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(513,'Thaumaturge',5,'Mor Dhona','North Silvertear','Gigas Sozu',2,29,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(514,'Thaumaturge',5,'Southern Thanalan','Zanr''ak','Iron Tortoise',6,19,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(515,'Thaumaturge',5,'Outer La Noscea','U''Ghamaro Mines','Synthetic Doblyn',6,23,8,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(516,'Thaumaturge',5,'South Shroud','Urth''s Gift','Ked',6,32,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(517,'Thaumaturge',5,'Western Thanalan','Cape Westwind','4th Cohort Hoplomachus',6,12,7,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(518,'Thaumaturge',5,'Eastern La Noscea','Agelyss Wise','2nd Cohort Signifier',6,27,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(519,'Arcanist',1,'Middle La Noscea','Zephyr Drift','Little Ladybug',3,22,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(520,'Arcanist',1,'Middle La Noscea','Zephyr Drift','Wharf Rat',3,21,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(521,'Arcanist',1,'Middle La Noscea','Zephyr Drift','Lost Lamb',3,23,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(522,'Arcanist',1,'Lower La Noscea','Cedarwood','Wind Sprite',3,28,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(523,'Arcanist',1,'Middle La Noscea','Summerford','Puk Hatchling',3,20,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(524,'Arcanist',1,'Lower La Noscea','Cedarwood','Nesting Buzzard',3,31,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(525,'Arcanist',1,'Middle La Noscea','Summerford','Bogy',3,20,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(526,'Arcanist',1,'Lower La Noscea','Cedarwood','Cave Bat',3,25,15,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(527,'Arcanist',1,'Lower La Noscea','Cedarwood','Galago',3,29,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(528,'Arcanist',1,'Middle La Noscea','Summerford','Grounded Pirate',3,20,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(529,'Arcanist',1,'Lower La Noscea','The God''s Grip','Lightning Sprite',3,20,32,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(530,'Arcanist',2,'Western La Noscea','Quarterstone','Sewer Mole',3,33,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(531,'Arcanist',2,'Lower La Noscea','Moraby Bay','Mossless Goobbue',3,32,15,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(532,'Arcanist',2,'Western La Noscea','Quarterstone','Fat Dodo',3,32,27,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(533,'Arcanist',2,'Western La Noscea','Quarterstone','Arbor Buzzard',3,30,29,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(534,'Arcanist',2,'Lower La Noscea','The God''s Grip','Qiqirn Eggdigger',3,18,35,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(535,'Arcanist',2,'Western La Noscea','Skull Valley','Dusk Bat',3,28,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(536,'Arcanist',2,'Western La Noscea','Skull Valley','Puk Hatchling',3,28,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(537,'Arcanist',2,'Western La Noscea','Skull Valley','Hedgemole',3,26,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(538,'Arcanist',2,'Western La Noscea','Skull Valley','Rothlyt Pelican',3,24,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(539,'Arcanist',2,'Western La Noscea','Skull Valley','Killer Mantis',3,22,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(540,'Arcanist',2,'Upper La Noscea','Oakwood','Bumble Beetle',3,12,23,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(541,'Arcanist',3,'East Shroud','Nine Ivies','Overgrown Ivy',4,23,29,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(542,'Arcanist',3,'Western Thanalan','The Footfalls','Lead Coblyn',4,13,10,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(543,'Arcanist',3,'South Shroud','Upper Paths','Kedtrap',4,21,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(544,'Arcanist',3,'Upper La Noscea','Oakwood','Coeurl Pup',4,9,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(545,'Arcanist',3,'South Shroud','Silent Arbor','Antelope Stag',4,22,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(546,'Arcanist',3,'North Shroud','Alder Springs','Balloon',4,17,26,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(547,'Arcanist',3,'Eastern Thanalan','Wellwick Wood','Chasm Buzzard',2,22,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(548,'Arcanist',3,'Eastern Thanalan','Wellwick Wood','Axe Beak',4,25,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(549,'Arcanist',3,'North Shroud','Alder Springs','Clay Golem',4,19,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(550,'Arcanist',3,'Southern Thanalan','Broken Water','Sandstone Golem',2,22,11,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(551,'Arcanist',3,'Central Shroud','Sorrel Haven','Blood Ziz',4,15,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(552,'Arcanist',3,'Central Shroud','Sorrel Haven','Lindwurm',4,13,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(553,'Arcanist',4,'Eastern La Noscea','Bloodshore','Qiqirn Gullroaster',4,26,32,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(554,'Arcanist',4,'Eastern La Noscea','Raincatcher Gully','Grass Raptor',4,16,25,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(555,'Arcanist',4,'Eastern La Noscea','Raincatcher Gully','Gigantoad',4,18,26,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(556,'Arcanist',4,'Southern Thanalan','Sagolii Desert','Sundrake',4,25,38,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(557,'Arcanist',4,'Eastern La Noscea','Bloodshore','Colibri',4,30,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(558,'Arcanist',4,'Outer La Noscea','The Long Climb','Coeurl',4,14,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(559,'Arcanist',4,'Eastern La Noscea','Raincatcher Gully','Mildeweld Goobbue',1,17,32,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(560,'Arcanist',4,'Coerthas Central Highlands','Dragonhead','Snow Wolf Pup',4,21,29,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(561,'Arcanist',4,'Coerthas Central Highlands','Dragonhead','Feral Croc',4,27,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(562,'Arcanist',4,'North Shroud','Proud Creek','Dryad',2,23,25,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(563,'Arcanist',4,'Coerthas Central Highlands','Providence Point','Taurus',4,32,12,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(564,'Arcanist',4,'East Shroud','Larkscall','Molted Ziz',4,25,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(565,'Arcanist',5,'Eastern Thanalan','The Burning Wall','Quartz Doblyn',4,30,25,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(566,'Arcanist',5,'Western La Noscea','The Isles of Umbra','Lammergeyer',4,12,36,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(567,'Arcanist',5,'East Shroud','Larkscall','3rd Cohort Laquearius',2,29,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(568,'Arcanist',5,'Mor Dhona','Fogfens','Nix',4,19,9,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(569,'Arcanist',5,'Mor Dhona','Fogfens','Mudpuppy',2,13,10,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(570,'Arcanist',5,'South Shroud','Urth''s Gift','Wild Hog',4,29,24,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(571,'Arcanist',5,'North Shroud','Proud Creek','Watchwolf',4,20,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(572,'Arcanist',5,'Mor Dhona','Fogfens','5th Cohort Laquearius',2,11,11,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(573,'Arcanist',5,'Coerthas Central Highlands','Boulder Downs','Snow Wolf',4,16,32,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(574,'Arcanist',5,'Coerthas Central Highlands','Natalan','Natalan Watchwolf',4,31,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(575,'Arcanist',5,'Western La Noscea','Sapsa Spawning Grounds','Axolotl',2,12,15,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(576,'Arcanist',5,'Souther Thanalan','Zahar''ak','Zahar''ak Battle Drake',4,31,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(577,'Arcanist',5,'Western Thanalan','Cape Westwind','4th Cohort Vanguard',4,12,7,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(578,'Order of the Twin Adder',1,'Eastern Thanalan','Sandgate','Amalj''aa Javelinier',3,19,27,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(579,'Order of the Twin Adder',1,'Eastern Thanalan','Halatali (Dungeon)','Heckler Imp',5,14,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(580,'Order of the Twin Adder',1,'Eastern Thanalan','Halatali (Dungeon)','Scythe Mantis',5,14,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(581,'Order of the Twin Adder',1,'Eastern Thanalan','Halatali (Dungeon)','Coliseum Python',5,14,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(582,'Order of the Twin Adder',1,'East Shroud','The Bramble Patch','Sylvan Scream',3,19,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(583,'Order of the Twin Adder',1,'Upper La Noscea','Oakwood','Kobold Pickman',3,13,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(584,'Order of the Twin Adder',1,'Southern Thanalan','Broken Water','Amalj''aa Bruiser',3,21,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(585,'Order of the Twin Adder',1,'North Shroud','Alder Springs','Ixali Deftalon',3,22,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(586,'Order of the Twin Adder',1,'Eastern Thanalan','Wellwick Wood','Amalj''aa Ranger',3,24,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(587,'Order of the Twin Adder',1,'Coerthas Central Highlands','Dragonhead','Ixali Fearcaller',1,31,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(588,'Order of the Twin Adder',2,'Southern Thanalan','Sagolii Desert','Amalj''aa Sniper',3,24,34,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(589,'Order of the Twin Adder',2,'Eastern La Noscea','Bloodshore','Kobold Missionary',3,28,26,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(590,'Order of the Twin Adder',2,'Upper La Noscea','Bronze Lake','Kobold Sidesman',3,26,19,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(591,'Order of the Twin Adder',2,'Southern Thanalan','The Sunken Temple of Qarn (Dungeon)','Temple Bee',4,25,12,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(592,'Order of the Twin Adder',2,'Southern Thanalan','The Sunken Temple of Qarn (Dungeon)','Temple Guardian',1,25,12,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(593,'Order of the Twin Adder',2,'Outer La Noscea','Iron Lake','Kobold Roundsman',3,22,14,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(594,'Order of the Twin Adder',2,'East Shroud','Larkscall','Sylvan Snarl ',3,23,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(595,'Order of the Twin Adder',2,'Western La Noscea','Halfstone','Shelfclaw Sahagin',3,18,21,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(596,'Order of the Twin Adder',2,'Southern Thanalan','Zanr''ak','Amalj''aa Lancer',3,22,16,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(597,'Order of the Twin Adder',2,'Outer La Noscea','U''Ghamaro Mines','U''Ghamaro Roundsman',3,23,9,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(598,'Order of the Twin Adder',3,'North Shroud','Proud Creek','Ixali Windtalon',3,20,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(599,'Order of the Twin Adder',3,'East Shroud','Sylphlands','Sylpheed Snarl',3,27,18,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(600,'Order of the Twin Adder',3,'Outer La Noscea','U''Ghamaro Mines','U''Ghamaro Quarryman',3,23,8,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(601,'Order of the Twin Adder',3,'Western La Noscea','Sapsa Spawning Grounds','Sapsa Shelftooth',3,17,15,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(602,'Order of the Twin Adder',3,'Southern Thanalan','Zahar''ak','Zahar''ak Pugilist',3,28,20,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(603,'Order of the Twin Adder',3,'Coerthas Central Highlands','Natalan','Natalan Swiftbeak',4,31,17,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(604,'Order of the Twin Adder',3,'Coerthas Central Highlands','Natalan','Natalan Boldwing',5,31,17,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(605,'Order of the Twin Adder',3,'Upper La Noscea','The Wanderer''s Palace (Dungeon)','Tonberry',7,26,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(606,'Order of the Twin Adder',3,'Upper La Noscea','The Wanderer''s Palace (Dungeon)','Bronze Beetle',6,26,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(607,'Order of the Twin Adder',3,'Upper La Noscea','The Wanderer''s Palace (Dungeon)','Keeper of Halidom',1,26,22,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(608,'Maelstrom',1,'Eastern Thanalan','Sandgate','Amalh''aa Hunter',3,19,28,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(609,'Maelstrom',1,'Eastern Thanalan','Halatali (Dungeon)','Heckler Imp',5,14,30,0);
INSERT INTO logs(_id,class,rank,region,area,enemy,num,x_loc,y_loc,done) VALUES(610,'Maelstrom',1,'Eastern Thanalan','Halatali (Dungeon(','Doctore',3,14,0,0);
UPDATE sqlite_sequence SET seq=610 WHERE rowid=10;
